/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RegistrarRole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.useraccount.UserAccount;
import javax.swing.JPanel;
import business.workqueue.CourseTransferRequest;
import business.workqueue.WorkRequest;
import business.workqueue.StudyAbroadApplication;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.CardLayout;

/**
 *
 * @author gerrysu
 */
public class RegistrarWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    
    /**
     * Creates new form RegistrarWorkAreaJPanel
     */
    public RegistrarWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        populateTable();
    }
public void populateTable() {
    DefaultTableModel model = (DefaultTableModel) tblWorkQueue.getModel();
    model.setRowCount(0);

    System.out.println("=== REGISTRAR DEBUG ===");
    System.out.println("Enterprise: " + enterprise.getName());
    
    int found = 0;
    int accepted = 0;

    // ⭐⭐⭐ 修改：查询所有 Network 中的所有 Enterprise 的所有 Organization ⭐⭐⭐
    for (business.network.Network network : business.getNetworkList()) {
        for (business.enterprise.Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (business.organization.Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                
                // 查询这个 Organization 的所有用户
                for (business.useraccount.UserAccount userAcc : org.getUserAccountDirectory().getUserAccountList()) {
                    
                    for (WorkRequest request : userAcc.getWorkQueue().getWorkRequestList()) {
                        if (request instanceof StudyAbroadApplication) {
                            found++;
                            StudyAbroadApplication app = (StudyAbroadApplication) request;
                            
                            System.out.println("Found app #" + found);
                            System.out.println("  Status: " + app.getStatus());
                            System.out.println("  University: " + app.getSelectedUniversity());

                            if ("Offer Accepted".equals(app.getStatus()) && 
                                app.getSelectedUniversity().contains(enterprise.getName())) {
                                
                                accepted++;
                                System.out.println("  ✅ MATCH! Adding to table...");

                                String studentName = "N/A";
                                if (app.getSender() != null && app.getSender().getEmployee() != null) {
                                    studentName = app.getSender().getEmployee().getName();
                                }

                                Object[] row = new Object[5];
                                row[0] = app;
                                row[1] = studentName;
                                row[2] = app.getSelectedUniversity();
                                row[3] = app.getStatus();
                                row[4] = "Ready for transcript";
                                model.addRow(row);
                            }
                        }
                    }
                }
            }
        }
    }
    
    System.out.println("Total apps found: " + found);
    System.out.println("Accepted & matching: " + accepted);
    System.out.println("Table rows: " + model.getRowCount());
    System.out.println("======================");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWorkQueue = new javax.swing.JTable();
        btnProcessTransfer = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblTitle.setText("Registrar Work Area");

        tblWorkQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Student Name", "Courses Requested", "Status", "Message"
            }
        ));
        jScrollPane2.setViewportView(tblWorkQueue);

        btnProcessTransfer.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnProcessTransfer.setText("Process Course Transfer");
        btnProcessTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessTransferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(btnProcessTransfer)
                .addGap(260, 343, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnProcessTransfer)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessTransferActionPerformed
       int selectedRow = tblWorkQueue.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null, 
            "Please select a student to issue transcript.");
        return;
    }

    StudyAbroadApplication app = (StudyAbroadApplication) tblWorkQueue.getValueAt(selectedRow, 0);

    CourseTransferRequest request = new CourseTransferRequest();
    request.setSender(app.getSender());
    request.setStatus("Pending");
    request.setMessage("Transcript request for " + app.getSelectedUniversity());

    ProcessCourseTransferJPanel panel = new ProcessCourseTransferJPanel(
        userProcessContainer, request, business);
    userProcessContainer.add("ProcessCourseTransfer", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProcessTransferActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessTransfer;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblWorkQueue;
    // End of variables declaration//GEN-END:variables
}
