/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VisaSpecialistRole;

import business.workqueue.StudyAbroadApplication;
import business.workqueue.VisaSupportRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author gerrysu
 */
public class ProcessVisaRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private VisaSupportRequest request;
    
    /**
     * Creates new form ProcessVisaRequestJPanel
     */
    public ProcessVisaRequestJPanel(JPanel userProcessContainer, VisaSupportRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        
        populateData();
    }
    
    private void populateData(){
    if(request.getSender() != null){
        txtStudent.setText(request.getSender().getEmployee().getName());
    }
    txtPassport.setText(request.getPassportNumber());
    txtCountry.setText(request.getIssuingCountry());

    StudyAbroadApplication app = request.getStudyAbroadApplication();
    if (app != null) {
        if (app.isAidApproved()) {
            double aidAmount = app.getGrantAmount();
            txtAid.setText("$" + String.format("%.2f", aidAmount));
            chkFinancial.setSelected(true); 
        } else if (app.isAidSaved()) {

            txtAid.setText("Pending Approval");
            chkFinancial.setSelected(false);
        } else {
            txtAid.setText("Not Available");
            chkFinancial.setSelected(false);
        }
    } else {
        txtAid.setText("N/A");
        chkFinancial.setSelected(false);
    }
    
    // Read-only fields
    txtStudent.setEnabled(false);
    txtPassport.setEnabled(false);
    txtCountry.setEnabled(false);
    txtAid.setEnabled(false);  
    
    // Status checks
    chkLegal.setSelected(request.isLegalCheckPassed());

    chkLegal.setEnabled(false); // Specialist cannot change these
    chkFinancial.setEnabled(false);
    
    // If already issued, show number
    if(request.isVisaIssued()){
        txtVisaNumber.setText(request.getVisaNumber());
        btnIssue.setEnabled(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIssue = new javax.swing.JButton();
        chkLegal = new javax.swing.JCheckBox();
        chkFinancial = new javax.swing.JCheckBox();
        lblTitle = new javax.swing.JLabel();
        lblStudent = new javax.swing.JLabel();
        lblPassport = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblVisaNumber = new javax.swing.JLabel();
        lblCheck = new javax.swing.JLabel();
        txtStudent = new javax.swing.JTextField();
        txtPassport = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtVisaNumber = new javax.swing.JTextField();
        lblAid = new javax.swing.JLabel();
        txtAid = new javax.swing.JTextField();

        btnIssue.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnIssue.setText("Generate Visa & Issue");
        btnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueActionPerformed(evt);
            }
        });

        chkLegal.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        chkLegal.setText("Legal Background Check Passed");

        chkFinancial.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        chkFinancial.setText("Financial Proof Verified");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle.setText("Issue Student Visa");

        lblStudent.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblStudent.setText("Student Name:");

        lblPassport.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblPassport.setText("Passport No:");

        lblCountry.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblCountry.setText("Destination Country:");

        lblVisaNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblVisaNumber.setText("Visa Number:");

        lblCheck.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblCheck.setText("Verification Status (ReadOnly):");

        txtStudent.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtPassport.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtCountry.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtVisaNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        lblAid.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblAid.setText("Finance Aid");

        txtAid.setEditable(false);
        txtAid.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkFinancial)
                                .addComponent(chkLegal))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPassport)
                                    .addComponent(lblStudent)
                                    .addComponent(lblCountry)
                                    .addComponent(lblVisaNumber)
                                    .addComponent(lblAid))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAid, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVisaNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lblCheck)))))
                .addContainerGap(287, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnIssue)
                .addGap(319, 319, 319))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudent)
                    .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassport)
                    .addComponent(txtPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVisaNumber)
                    .addComponent(txtVisaNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAid)
                    .addComponent(txtAid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addComponent(lblCheck)
                .addGap(18, 18, 18)
                .addComponent(chkLegal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkFinancial)
                .addGap(138, 138, 138)
                .addComponent(btnIssue)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueActionPerformed
        // TODO add your handling code here:
        Random rand = new Random();
        String visaNum = "VISA-" + (100000 + rand.nextInt(900000));
        
        request.setVisaIssued(true);
        request.setVisaNumber(visaNum);
        request.setStatus("Visa Issued");
        request.setResult("Visa Approved: " + visaNum);
        
        txtVisaNumber.setText(visaNum);
        btnIssue.setEnabled(false);
        
        JOptionPane.showMessageDialog(null, "Visa Generated Successfully!\nNumber: " + visaNum);
        
        goBack();
        
        
    }//GEN-LAST:event_btnIssueActionPerformed

    private void goBack() {
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIssue;
    private javax.swing.JCheckBox chkFinancial;
    private javax.swing.JCheckBox chkLegal;
    private javax.swing.JLabel lblAid;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblPassport;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVisaNumber;
    private javax.swing.JTextField txtAid;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtPassport;
    private javax.swing.JTextField txtStudent;
    private javax.swing.JTextField txtVisaNumber;
    // End of variables declaration//GEN-END:variables
}
