/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MobilityOfficerRole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.InternationalAdmissionsOrganization;
import business.organization.Organization;
import business.workqueue.NominationRequest;
import business.workqueue.StudyAbroadApplication;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import business.organization.FinancialAidOrganization;
import business.workqueue.FinancialClearanceRequest;

/**
 *
 * @author gerrysu
 */
public class ProcessApplicationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private StudyAbroadApplication request;
    private EcoSystem system;
    
    /**
     * Creates new form ProcessApplicationJPanel
     */
    public ProcessApplicationJPanel(JPanel userProcessContainer, StudyAbroadApplication request, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.system = system;
        
        populateData();        

    }

    private void populateData(){
        txtStudent.setText(request.getSender().getEmployee().getName());
        txtMajor.setText(request.getMajor());
        txtGPA.setText(String.valueOf(request.getCurrentGPA()));
        txtTargetUni.setText(request.getSelectedUniversity());
        
        // Disable editing
        txtStudent.setEnabled(false);
        txtMajor.setEnabled(false);
        txtGPA.setEnabled(false);
        txtTargetUni.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblStudent = new javax.swing.JLabel();
        lblMajor = new javax.swing.JLabel();
        lblGPA = new javax.swing.JLabel();
        lblTargetUni = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        txtStudent = new javax.swing.JTextField();
        txtMajor = new javax.swing.JTextField();
        txtGPA = new javax.swing.JTextField();
        txtTargetUni = new javax.swing.JTextField();
        txtMessage = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Review Application");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        lblStudent.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblStudent.setText("Student:");
        add(lblStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        lblMajor.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblMajor.setText("Major:");
        add(lblMajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        lblGPA.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblGPA.setText("GPA:");
        add(lblGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        lblTargetUni.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTargetUni.setText("Target Uni:");
        add(lblTargetUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        lblMessage.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblMessage.setText("Officer Comments:");
        add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        txtStudent.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(txtStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 283, -1));

        txtMajor.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(txtMajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 283, -1));

        txtGPA.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(txtGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 283, -1));

        txtTargetUni.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(txtTargetUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 283, -1));

        txtMessage.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 283, 89));

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 690, -1, -1));

        btnApprove.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnApprove.setText("Nominate Student");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 488, -1, -1));

        btnReject.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnReject.setText("Reject Application");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        request.setStatus("Rejected");
        request.setResult("Rejected: " + txtMessage.getText());
        JOptionPane.showMessageDialog(null, "Application Rejected.");
        goBack();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        // 1. Update status
        request.setStatus("Nominated");
        request.setResult("Approved by Mobility Officer");
        
        // 2. Find Host University and Admission Org
        Organization targetOrg = null;
        String targetUniName = request.getSelectedUniversity();
        
        for (Network n : system.getNetworkList()){
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                // Check if this is the target university (Exact string match for now)
                if (e.getName().equalsIgnoreCase(targetUniName) && e instanceof business.enterprise.HostUniversityEnterprise){
                    // Find Admissions Org
                    for (Organization o : e.getOrganizationDirectory().getOrganizationList()){
                        if (o instanceof InternationalAdmissionsOrganization){
                            targetOrg = o;
                            break;
                        }
                    }
                }
            }
        }
        
        if (targetOrg != null){
            // 3. Create Nomination Request
            NominationRequest nomination = new NominationRequest();
            nomination.setStudentApplication(request); // Link original app
            nomination.setMessage("Nomination for " + request.getSender().getEmployee().getName());
            nomination.setSender(request.getSender()); // Or set sender as Mobility Officer
            nomination.setStatus("Nominated");
            
            targetOrg.getWorkQueue().getWorkRequestList().add(nomination);
            
            Organization finAidOrg = null;
            for (Network n : system.getNetworkList()) {
                for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                    if (e instanceof business.enterprise.HomeUniversityEnterprise) {
                        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                            if (o instanceof FinancialAidOrganization) {
                                finAidOrg = o;
                                break;
                            }
                        }
                    }
                    if (finAidOrg != null) break;
                }
                if (finAidOrg != null) break;
            }

            if (finAidOrg != null) {
                FinancialClearanceRequest finRequest = new FinancialClearanceRequest();
                finRequest.setStudentApplication(request);
                finRequest.setSender(request.getSender());
                finRequest.setMessage("Financial clearance needed for " + 
                                     request.getSender().getEmployee().getName());
                finRequest.setStatus("Pending Review");

                // Set default grant amount (can be estimated based on GPA or other criteria)
                


                finAidOrg.getWorkQueue().getWorkRequestList().add(finRequest);

                System.out.println("✓ Created FinancialClearanceRequest for " + 
                                  request.getSender().getEmployee().getName());
            }

            JOptionPane.showMessageDialog(null, "Student Nominated! Sent to " + targetUniName);
            goBack();
        } else {
            JOptionPane.showMessageDialog(null, "Error: Could not find Host University '" + targetUniName + "' in the system.");
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageActionPerformed

    private void goBack(){
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MobilityOfficerWorkAreaJPanel dwjp = (MobilityOfficerWorkAreaJPanel) component;
        dwjp.populateTable(); // Refresh the table
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblMajor;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JLabel lblTargetUni;
    private javax.swing.JTextField txtGPA;
    private javax.swing.JTextField txtMajor;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtStudent;
    private javax.swing.JTextField txtTargetUni;
    // End of variables declaration//GEN-END:variables
}
